kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bucketrepo-bucketrepo
  namespace: jx
  labels:
    app: bucketrepo-bucketrepo
    chart: "bucketrepo-0.6.1"
    release: bucketrepo
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'bucketrepo'
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"

