# Source: minio/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: minio
  labels:
    app: minio
    chart: minio-5.3.0
    release: minio
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: local
  data:
  - name: rootUser
    key: rootUser
    property: rootUser
  - name: rootPassword
    key: rootPassword
    property: rootPassword
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'minio'
      labels:
        app: minio
        chart: minio-5.3.0
        release: minio
        heritage: Helm
    type: Opaque
