# Source: minio/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
    chart: minio-5.3.0
    release: minio
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'minio'
    wave.pusher.com/update-on-config-change: 'true'
  namespace: jx
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: minio
      release: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
        release: minio
      annotations:
        checksum/secrets: d944e061e3547a55c0984759a8963f7d4b9b526a1b19e187f08c734b0eb6e5f3
        checksum/config: 3e4529cf5b33355ccb9a5e8167ba93d70e4493762f97b73027ef4c1f4c6ee3d5
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccountName: minio-sa
      containers:
      - name: minio
        image: "quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z"
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/sh"
        - "-ce"
        - "/usr/bin/docker-entrypoint.sh minio server /export -S /etc/minio/certs/ --address :9000 --console-address :9001"
        volumeMounts:
        - name: minio-user
          mountPath: "/tmp/credentials"
          readOnly: true
        - name: export
          mountPath: /export
        ports:
        - name: http
          containerPort: 9000
        - name: http-console
          containerPort: 9001
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio
              key: rootUser
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio
              key: rootPassword
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: "public"
        resources:
          requests:
            memory: 16Gi
        securityContext:
          readOnlyRootFilesystem: false
      volumes:
      - name: export
        persistentVolumeClaim:
          claimName: minio
      - name: minio-user
        secret:
          secretName: minio
