apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://chartmuseum.jx.svc.cluster.local
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
    registry: 10.97.57.112
  environments:
  - key: dev
    owner: iMckify
    repository: pipeline-cluster
  - key: staging
  - key: production
  ingress:
    domain: 192.168.49.2.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: iMckify
  repository: chartmuseum
  secretStorage: local
  vault: {}
  webhook: lighthouse
