filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: oci://docker-registry-jx.192.168.49.2.nip.io/charts
releases:
- chart: dev/react-spring
  version: 0.0.74
  name: react-spring
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
