filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-production
repositories:
- name: dev
  url: http://bucketrepo-jx.192.168.49.2.nip.io/bucketrepo/charts
releases:
- chart: dev/react-spring
  version: 0.0.27
  name: react-spring
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
