resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
# set volume for bucketrepo pod
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  existingClaim: ""
  storageClass: ""
  hostPath: /home/rokas/volumes/bucketrepo
