resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
# set volume for bucketrepo pod
persistence:
  enabled: true
  existingClaim: bucketrepo-bucketrepo
  accessMode: ReadWriteOnce
  storageClassName: standard
deployment:
  enabled: false
dependencies:
  - name: bucketrepo
    version: "0.6.1"
    repository: "jxgh"