apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: tekton.dev|PipelineRun|default|pullrequest
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/839765fb594490586e51b25e12b93609441235f8/tasks/git-clone/git-clone-pr.yaml
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        spec: null
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/environment/pullrequest.yaml@versionStream
          name: ""
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-env-pr.yaml@versionStream
          name: ""
          resources: {}
        - image: alpine:latest
          name: list-bucketrepo-charts
          resources: {}
          script: |
            #!/bin/sh
            apk update
            apk add curl
            echo "Listing charts from bucketrepo.jx:"
            curl -s http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/index.yaml
        - name: make-pr
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
