apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: tekton.dev|PipelineRun|default|release
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/839765fb594490586e51b25e12b93609441235f8/tasks/git-clone/git-clone.yaml
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        spec: null
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/environment/release.yaml@versionStream
          name: ""
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: admin-log
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
